In [2]:
import pandas as pd
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns

# Setting the style of the plots
sns.set_style('whitegrid')
plt.style.use('fivethirtyeight')

# Downloading dataset from Kaggle
kagglehub.login()
file_path = kagglehub.dataset_download("krzysztofjamroz/apartment-prices-in-poland", path="apartments_pl_2024_06.csv")

# Loading data into DataFrame
df = pd.read_csv(file_path)

df.head()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,pharmacyDistance,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price
0,811891f98a870dfd6e414374a0a85560,szczecin,blockOfFlats,47.00,2.0,6.0,12.0,1981.0,53.428544,14.552812,...,0.085,condominium,concreteSlab,NaN,no,yes,yes,no,yes,449000
1,adaf636d0c44d8d9325bce42403eefee,szczecin,apartmentBuilding,88.22,3.0,1.0,2.0,2000.0,53.449093,14.516844,...,0.668,condominium,brick,premium,yes,yes,no,no,no,950000
2,9b957bd60885a469c96f17b58a914f4b,szczecin,apartmentBuilding,117.00,5.0,4.0,4.0,NaN,53.443096,14.561348,...,0.229,udział,brick,premium,yes,yes,no,no,no,1099000
3,74fef2ff7135bc70797a3fbfd7d44ed6,szczecin,blockOfFlats,33.31,1.0,1.0,4.0,1963.0,53.436100,14.541200,...,0.388,cooperative,brick,NaN,yes,no,no,yes,yes,380000
4,77cc78c75b0d09bf84d6d3124a28803c,szczecin,blockOfFlats,56.00,3.0,7.0,7.0,2018.0,53.447465,14.557811,...,0.178,condominium,brick,premium,yes,yes,yes,yes,yes,799000

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21501 entries, 0 to 21500
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21501 non-null  str
 1   city                  21501 non-null  str
 2   type                  17104 non-null  str
 3   squareMeters          21501 non-null  float64
 4   rooms                 21501 non-null  float64
 5   floor                 17928 non-null  float64
 6   floorCount            21292 non-null  float64
 7   buildYear             18121 non-null  float64
 8   latitude              21501 non-null  float64
 9   longitude             21501 non-null  float64
 10  centreDistance        21501 non-null  float64
 11  poiCount              21501 non-null  float64
 12  schoolDistance        21490 non-null  float64
 13  clinicDistance        21438 non-null  float64
 14  postOfficeDistance    21481 non-null  float64
 15  kindergartenDistance  21482 non-null  float64
 16  restaurantDistance    21470 non-null  float64
 17  collegeDistance       20917 non-null  float64
 18  pharmacyDistance      21471 non-null  float64
 19  ownership             21501 non-null  str
 20  buildingMaterial      12709 non-null  str
 21  condition             5580 non-null   str
 22  hasParkingSpace       21501 non-null  str
 23  hasBalcony            21501 non-null  str
 24  hasElevator           20541 non-null  str
 25  hasSecurity           21501 non-null  str
 26  hasStorageRoom        21501 non-null  str
 27  price                 21501 non-null  int64
dtypes: float64(16), int64(1), str(11)
memory usage: 4.6 MB

In [ ]:
df.describe()

,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,centreDistance,poiCount,schoolDistance,clinicDistance,postOfficeDistance,kindergartenDistance,restaurantDistance,collegeDistance,pharmacyDistance,price
count,21501.000000,21501.000000,17928.000000,21292.000000,18121.000000,21501.000000,21501.000000,21501.000000,21501.000000,21490.000000,21438.000000,21481.000000,21482.000000,21470.000000,20917.000000,21471.000000,2.150100e+04
mean,56.968572,2.622948,3.404786,5.474826,1986.774129,51.992750,19.496174,4.431978,20.542951,0.407994,0.970949,0.510007,0.357013,0.335759,1.440711,0.347109,8.238679e+05
std,20.617717,0.892924,2.606225,3.407545,32.796668,1.313801,1.754150,2.783001,23.905646,0.442670,0.882206,0.474219,0.414213,0.433327,1.103795,0.427962,4.311267e+05
min,25.000000,1.000000,1.000000,1.000000,1850.000000,49.982066,14.447127,0.020000,0.000000,0.005000,0.005000,0.002000,0.001000,0.001000,0.006000,0.001000,1.910000e+05
25%,42.690000,2.000000,2.000000,3.000000,1969.000000,51.103600,18.539977,2.130000,7.000000,0.178000,0.361000,0.238000,0.154000,0.112000,0.565000,0.136000,5.490000e+05
50%,52.810000,3.000000,3.000000,4.000000,1993.000000,52.194157,19.914700,4.130000,14.000000,0.289000,0.677000,0.392000,0.256000,0.224000,1.121000,0.235000,7.218240e+05
75%,66.300000,3.000000,4.000000,7.000000,2016.000000,52.379000,20.988591,6.250000,24.000000,0.462000,1.244000,0.621000,0.411000,0.402000,2.050000,0.403000,9.650000e+05
max,150.000000,6.000000,29.000000,29.000000,2024.000000,54.582870,23.208873,16.480000,212.000000,4.920000,4.918000,4.801000,4.767000,4.928000,5.000000,4.802000,3.000000e+06

In [3]:
from data_loader import load_data
from preprocess import clean_data, encode_features

df_cleaned = clean_data(df)
df_encoded = encode_features(df_cleaned)

In [4]:
df_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 21501 entries, 0 to 21500
Data columns (total 46 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   squareMeters                   21501 non-null  float64
 1   rooms                          21501 non-null  float64
 2   floor                          21501 non-null  float64
 3   floorCount                     21501 non-null  float64
 4   buildYear                      21501 non-null  float64
 5   latitude                       21501 non-null  float64
 6   longitude                      21501 non-null  float64
 7   centreDistance                 21501 non-null  float64
 8   poiCount                       21501 non-null  float64
 9   schoolDistance                 21501 non-null  float64
 10  clinicDistance                 21501 non-null  float64
 11  postOfficeDistance             21501 non-null  float64
 12  kindergartenDistance           21501 non-null  float64
 13  restaurantDistance             21501 non-null  float64
 14  collegeDistance                21501 non-null  float64
 15  pharmacyDistance               21501 non-null  float64
 16  hasParkingSpace                21501 non-null  int64
 17  hasBalcony                     21501 non-null  int64
 18  hasSecurity                    21501 non-null  int64
 19  hasStorageRoom                 21501 non-null  int64
 20  price                          21501 non-null  int64
 21  city_bydgoszcz                 21501 non-null  int64
 22  city_czestochowa               21501 non-null  int64
 23  city_gdansk                    21501 non-null  int64
 24  city_gdynia                    21501 non-null  int64
 25  city_katowice                  21501 non-null  int64
 26  city_krakow                    21501 non-null  int64
 27  city_lodz                      21501 non-null  int64
 28  city_lublin                    21501 non-null  int64
 29  city_poznan                    21501 non-null  int64
 30  city_radom                     21501 non-null  int64
 31  city_rzeszow                   21501 non-null  int64
 32  city_szczecin                  21501 non-null  int64
 33  city_warszawa                  21501 non-null  int64
 34  city_wroclaw                   21501 non-null  int64
 35  type_blockOfFlats              21501 non-null  int64
 36  type_n/d                       21501 non-null  int64
 37  type_tenement                  21501 non-null  int64
 38  ownership_cooperative          21501 non-null  int64
 39  ownership_udział               21501 non-null  int64
 40  buildingMaterial_concreteSlab  21501 non-null  int64
 41  buildingMaterial_n/d           21501 non-null  int64
 42  condition_n/d                  21501 non-null  int64
 43  condition_premium              21501 non-null  int64
 44  hasElevator_no                 21501 non-null  int64
 45  hasElevator_yes                21501 non-null  int64
dtypes: float64(16), int64(30)
memory usage: 7.5 MB

In [5]:
df_encoded.describe()

,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,centreDistance,poiCount,schoolDistance,...,type_n/d,type_tenement,ownership_cooperative,ownership_udział,buildingMaterial_concreteSlab,buildingMaterial_n/d,condition_n/d,condition_premium,hasElevator_no,hasElevator_yes
count,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,...,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000,21501.000000
mean,56.968572,2.622948,3.306916,5.459327,1986.086856,51.992750,19.496174,4.431978,20.542951,0.408049,...,0.204502,0.137575,0.102925,0.000140,0.143714,0.408911,0.740477,0.139296,0.463885,0.491466
std,20.617717,0.892924,2.435810,3.394864,32.400981,1.313801,1.754150,2.783001,23.905646,0.442570,...,0.403347,0.344461,0.303869,0.011812,0.350808,0.491644,0.438383,0.346263,0.498706,0.499939
min,25.000000,1.000000,1.000000,1.000000,1850.000000,49.982066,14.447127,0.020000,0.000000,0.005000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,42.690000,2.000000,2.000000,3.000000,1970.000000,51.103600,18.539977,2.130000,7.000000,0.178000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,52.810000,3.000000,3.000000,4.000000,1993.000000,52.194157,19.914700,4.130000,14.000000,0.289000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,66.300000,3.000000,4.000000,7.000000,2014.000000,52.379000,20.988591,6.250000,24.000000,0.462000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,150.000000,6.000000,29.000000,29.000000,2024.000000,54.582870,23.208873,16.480000,212.000000,4.920000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000